import type { Metadata } from 'next';
import { Noto_Sans_Hebrew } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const noto_sans_hebrew = Noto_Sans_Hebrew({
  weight: '700',
  subsets: ['hebrew'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${noto_sans_hebrew.className}`}>{children}</body>
    </html>
  );
}
